openapi: 3.0.0
info:
  title: UIDAI Aadhaar API (POC+)
  version: 1.0.0
  description: Dummy Aadhaar verification APIs for POC

servers:
  - url: http://localhost:5000/api/v1

paths:
  /aadhaar/verify:
    post:
      summary: Verify Aadhaar number
      description: Validates if Aadhaar number is valid (12 digits)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhaar_number:
                  type: string
                  pattern: '^[0-9]{12}$'
                  example: "123456789012"
              required:
                - aadhaar_number
      responses:
        '200':
          description: Valid Aadhaar
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "valid"
                  message:
                    type: string
        '400':
          description: Invalid Aadhaar
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "invalid"
                  error:
                    type: string

  /aadhaar/demographics:
    post:
      summary: Get demographic details
      description: Fetch masked demographic info for Aadhaar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhaar_number:
                  type: string
                  pattern: '^[0-9]{12}$'
                consent:
                  type: boolean
                  example: true
              required:
                - aadhaar_number
                - consent
      responses:
        '200':
          description: Demographics retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  dob:
                    type: string
                  gender:
                    type: string
                  address:
                    type: string
        '400':
          description: Invalid request
        '403':
          description: Consent not provided

  /aadhaar/otp/generate:
    post:
      summary: Generate OTP for Aadhaar
      description: Sends OTP to registered mobile for verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhaar_number:
                  type: string
                  pattern: '^[0-9]{12}$'
              required:
                - aadhaar_number
      responses:
        '200':
          description: OTP sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  transaction_id:
                    type: string
                  message:
                    type: string
        '400':
          description: Invalid Aadhaar number
        '429':
          description: Rate limit exceeded
# Test change
