openapi: 3.0.0
info:
  title: UIDAI Aadhaar API
  version: 1.2.57
  description: Dummy Aadhaar verification APIs for POC

servers:
  - url: http://localhost:5001/api/v1

paths:
  /aadhaar/verify:
    post:
      summary: Verify Aadhaar number
      description: Validates if Aadhaar number is valid (2 digits)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhaar_number:
                  type: string
                  pattern: '^[0-9]{12}$'
                  example: "123456789012"
              required:
                - aadhaar_number
      responses:
        '200':
          description: Valid Aadhaar
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "valid"
                  message:
                    type: string
                    example: "Aadhaar number is valid"
        '400':
          description: Invalid Aadhaar
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "invalid"
                  error:
                    type: string
                    example: "Invalid Aadhaar format"

  /aadhaar/demographics:
    post:
      summary: Get demographic details
      description: Fetch masked demographic info for Aadhaar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                aadhaar_number:
                  type: string
                  pattern: '^[0-9]{12}$'
                  example: "123456789012"
                consent:
                  type: boolean
                  example: true
              required:
                - aadhaar_number
                - consent
      responses:
        '200':
          description: Demographics retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "John Doe"
                  dob:
                    type: string
                    format: date
                    example: "1990-01-01"
                  gender:
                    type: string
                    example: "M"
                  address:
                    type: string
                    example: "123 Main St, City"
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Consent not provided
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Consent required"